# fly.toml app configuration file generated for delicate-cherry-9699 on 2024-03-27T13:22:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'delicate-cherry-9699'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 9010
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
